<?xml version="1.0"?>
<map version="1.0.1">
  <!--Generated by Minder 1.13.1-->
  <node ID="id_0" FOLDED="false" POSITION="left" TEXT="Level up" BACKGROUND_COLOR="#000000">
    <edge STYLE="bezier" COLOR="#000000" WIDTH="4"/>
    <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
    <node ID="id_1" FOLDED="false" POSITION="left" TEXT="&#x627;&#x644;&#x625;&#x635;&#x644;&#x627;&#x62D;" BACKGROUND_COLOR="#c6262e">
      <edge STYLE="bezier" COLOR="#c6262e" WIDTH="4"/>
      <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
    </node>
    <node ID="id_2" FOLDED="false" POSITION="right" TEXT="Learn English \ street" BACKGROUND_COLOR="#3689e6">
      <edge STYLE="bezier" COLOR="#3689e6" WIDTH="4"/>
      <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
      <node ID="id_3" FOLDED="false" POSITION="right" TEXT="Laungage" BACKGROUND_COLOR="#715344">
        <edge STYLE="bezier" COLOR="#715344" WIDTH="4"/>
        <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
        <node ID="id_4" FOLDED="false" POSITION="right" TEXT="Verb + Phrase + Conju" BACKGROUND_COLOR="#715344">
          <edge STYLE="bezier" COLOR="#715344" WIDTH="4"/>
          <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
        </node>
        <node ID="id_5" FOLDED="false" POSITION="right" TEXT="Syntax" BACKGROUND_COLOR="#715344">
          <edge STYLE="bezier" COLOR="#715344" WIDTH="4"/>
          <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
        </node>
        <node ID="id_6" FOLDED="false" POSITION="right" TEXT="Read" BACKGROUND_COLOR="#715344">
          <edge STYLE="linear" COLOR="#715344" WIDTH="4"/>
          <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          <node ID="id_7" FOLDED="false" POSITION="right" TEXT="Books" BACKGROUND_COLOR="#715344">
            <edge STYLE="bezier" COLOR="#715344" WIDTH="4"/>
            <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          </node>
          <node ID="id_8" FOLDED="false" POSITION="right" TEXT="Poem" BACKGROUND_COLOR="#715344">
            <edge STYLE="bezier" COLOR="#715344" WIDTH="4"/>
            <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          </node>
          <node ID="id_9" FOLDED="false" POSITION="right" TEXT="Dialogue and Subtitles" BACKGROUND_COLOR="#715344">
            <edge STYLE="bezier" COLOR="#715344" WIDTH="4"/>
            <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          </node>
        </node>
        <node ID="id_10" FOLDED="false" POSITION="right" TEXT="Listen" BACKGROUND_COLOR="#715344">
          <edge STYLE="linear" COLOR="#715344" WIDTH="4"/>
          <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          <node ID="id_11" FOLDED="false" POSITION="right" TEXT="Podcasts" BACKGROUND_COLOR="#715344">
            <edge STYLE="bezier" COLOR="#715344" WIDTH="4"/>
            <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          </node>
          <node ID="id_12" FOLDED="false" POSITION="right" TEXT="Dialogue (movies and games" BACKGROUND_COLOR="#715344">
            <edge STYLE="bezier" COLOR="#715344" WIDTH="4"/>
            <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          </node>
        </node>
      </node>
      <node ID="id_13" FOLDED="false" POSITION="right" TEXT="Write" BACKGROUND_COLOR="#4e9a06">
        <edge STYLE="bezier" COLOR="#4e9a06" WIDTH="4"/>
        <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
        <node ID="id_14" FOLDED="false" POSITION="right" TEXT="Phrases" BACKGROUND_COLOR="#4e9a06">
          <edge STYLE="bezier" COLOR="#4e9a06" WIDTH="4"/>
          <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
        </node>
        <node ID="id_15" FOLDED="false" POSITION="right" TEXT="Poem" BACKGROUND_COLOR="#4e9a06">
          <edge STYLE="bezier" COLOR="#4e9a06" WIDTH="4"/>
          <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
        </node>
        <node ID="id_16" FOLDED="false" POSITION="right" TEXT="Chat with people" BACKGROUND_COLOR="#4e9a06">
          <edge STYLE="bezier" COLOR="#4e9a06" WIDTH="4"/>
          <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
        </node>
      </node>
      <node ID="id_17" FOLDED="false" POSITION="right" TEXT="Talk" BACKGROUND_COLOR="#3689e6">
        <edge STYLE="bezier" COLOR="#3689e6" WIDTH="4"/>
        <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
        <node ID="id_18" FOLDED="false" POSITION="right" TEXT="Talk with yourself" BACKGROUND_COLOR="#3689e6">
          <edge STYLE="bezier" COLOR="#3689e6" WIDTH="4"/>
          <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
        </node>
        <node ID="id_19" FOLDED="false" POSITION="right" TEXT="Repeat with dialogue " BACKGROUND_COLOR="#3689e6">
          <edge STYLE="bezier" COLOR="#3689e6" WIDTH="4"/>
          <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
        </node>
        <node ID="id_20" FOLDED="false" POSITION="right" TEXT="Talk with strange people" BACKGROUND_COLOR="#3689e6">
          <edge STYLE="bezier" COLOR="#3689e6" WIDTH="4"/>
          <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
        </node>
      </node>
    </node>
    <node ID="id_21" FOLDED="false" POSITION="right" TEXT="Learning Linux" BACKGROUND_COLOR="#f37329">
      <edge STYLE="bezier" COLOR="#f37329" WIDTH="4"/>
      <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
      <node ID="id_22" FOLDED="false" POSITION="right" TEXT="GUI" BACKGROUND_COLOR="#f9c440">
        <edge STYLE="bezier" COLOR="#f9c440" WIDTH="4"/>
        <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
        <node ID="id_23" FOLDED="false" POSITION="right" TEXT="Understand Interface" BACKGROUND_COLOR="#f9c440">
          <edge STYLE="bezier" COLOR="#f9c440" WIDTH="4"/>
          <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
        </node>
        <node ID="id_24" FOLDED="false" POSITION="right" TEXT="Edit things from gui" BACKGROUND_COLOR="#f9c440">
          <edge STYLE="linear" COLOR="#f9c440" WIDTH="4"/>
          <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          <node ID="id_25" FOLDED="false" POSITION="right" TEXT="Users" BACKGROUND_COLOR="#f9c440">
            <edge STYLE="bezier" COLOR="#f9c440" WIDTH="4"/>
            <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          </node>
          <node ID="id_26" FOLDED="false" POSITION="right" TEXT="Password" BACKGROUND_COLOR="#f9c440">
            <edge STYLE="bezier" COLOR="#f9c440" WIDTH="4"/>
            <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          </node>
          <node ID="id_27" FOLDED="false" POSITION="right" TEXT="Permissions" BACKGROUND_COLOR="#f9c440">
            <edge STYLE="bezier" COLOR="#f9c440" WIDTH="4"/>
            <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          </node>
          <node ID="id_28" FOLDED="false" POSITION="right" TEXT="etc..." BACKGROUND_COLOR="#f9c440">
            <edge STYLE="bezier" COLOR="#f9c440" WIDTH="4"/>
            <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          </node>
        </node>
      </node>
      <node ID="id_29" FOLDED="false" POSITION="right" TEXT="CLI" BACKGROUND_COLOR="#310519">
        <edge STYLE="bezier" COLOR="#310519" WIDTH="4"/>
        <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
        <node ID="id_30" FOLDED="false" POSITION="right" TEXT="Shortcuts Terminal" BACKGROUND_COLOR="#310519">
          <edge STYLE="bezier" COLOR="#310519" WIDTH="4"/>
          <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
        </node>
        <node ID="id_31" FOLDED="false" POSITION="right" TEXT="Difference Shell" BACKGROUND_COLOR="#310519">
          <edge STYLE="linear" COLOR="#310519" WIDTH="4"/>
          <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          <node ID="id_32" FOLDED="false" POSITION="right" TEXT="Bash" BACKGROUND_COLOR="#310519">
            <edge STYLE="bezier" COLOR="#310519" WIDTH="4"/>
            <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          </node>
          <node ID="id_33" FOLDED="false" POSITION="right" TEXT="Zsh" BACKGROUND_COLOR="#310519">
            <edge STYLE="bezier" COLOR="#310519" WIDTH="4"/>
            <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          </node>
          <node ID="id_34" FOLDED="false" POSITION="right" TEXT="Fish" BACKGROUND_COLOR="#310519">
            <edge STYLE="bezier" COLOR="#310519" WIDTH="4"/>
            <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          </node>
        </node>
        <node ID="id_35" FOLDED="false" POSITION="right" TEXT="Command Line" BACKGROUND_COLOR="#310519">
          <edge STYLE="linear" COLOR="#310519" WIDTH="4"/>
          <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          <node ID="id_36" FOLDED="false" POSITION="right" TEXT="File and Directories" BACKGROUND_COLOR="#310519">
            <edge STYLE="bezier" COLOR="#310519" WIDTH="4"/>
            <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          </node>
          <node ID="id_37" FOLDED="false" POSITION="right" TEXT="Users and Permissions" BACKGROUND_COLOR="#310519">
            <edge STYLE="bezier" COLOR="#310519" WIDTH="4"/>
            <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          </node>
          <node ID="id_38" FOLDED="false" POSITION="right" TEXT="Tools" BACKGROUND_COLOR="#310519">
            <edge STYLE="bezier" COLOR="#310519" WIDTH="4"/>
            <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          </node>
          <node ID="id_39" FOLDED="false" POSITION="right" TEXT="Configuration" BACKGROUND_COLOR="#310519">
            <edge STYLE="bezier" COLOR="#310519" WIDTH="4"/>
            <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          </node>
          <node ID="id_40" FOLDED="false" POSITION="right" TEXT="Shell Scripts" BACKGROUND_COLOR="#310519">
            <edge STYLE="bezier" COLOR="#310519" WIDTH="4"/>
            <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          </node>
        </node>
      </node>
      <node ID="id_41" FOLDED="false" POSITION="right" TEXT="Folders and Files system" BACKGROUND_COLOR="#4d4a4a">
        <edge STYLE="bezier" COLOR="#4d4a4a" WIDTH="4"/>
        <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
        <node ID="id_42" FOLDED="false" POSITION="right" TEXT="Structure of files and folders" BACKGROUND_COLOR="#4d4a4a">
          <edge STYLE="bezier" COLOR="#4d4a4a" WIDTH="4"/>
          <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
        </node>
        <node ID="id_43" FOLDED="false" POSITION="right" TEXT="The cause of the and files" BACKGROUND_COLOR="#4d4a4a">
          <edge STYLE="bezier" COLOR="#4d4a4a" WIDTH="4"/>
          <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
        </node>
      </node>
    </node>
  </node>
</map>
