<?xml version="1.0"?>
<map version="1.0.1">
  <!--Generated by Minder 1.13.1-->
  <node ID="id_0" TEXT="Level up" FOLDED="false" COLOR="#000000" POSITION="left">
    <edge STYLE="bezier" COLOR="#000000" WIDTH="4"/>
    <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
    <node ID="id_1" TEXT="Addiction" FOLDED="false" COLOR="#f37329" POSITION="left">
      <edge STYLE="bezier" COLOR="#f37329" WIDTH="4"/>
      <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
      <node ID="id_2" TEXT="Pornography" FOLDED="false" COLOR="#f37329" POSITION="left">
        <edge STYLE="bezier" COLOR="#f37329" WIDTH="4"/>
        <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
      </node>
      <node ID="id_3" TEXT="Phone" FOLDED="false" COLOR="#f37329" POSITION="left">
        <edge STYLE="bezier" COLOR="#f37329" WIDTH="4"/>
        <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
      </node>
    </node>
    <node ID="id_4" TEXT="Learn English \ street" FOLDED="false" COLOR="#3689e6" POSITION="right">
      <edge STYLE="bezier" COLOR="#3689e6" WIDTH="4"/>
      <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
      <node ID="id_5" TEXT="Laungage" FOLDED="false" COLOR="#715344" POSITION="right">
        <edge STYLE="bezier" COLOR="#715344" WIDTH="4"/>
        <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
        <node ID="id_6" TEXT="Verb + Phrase + Conju" FOLDED="false" COLOR="#715344" POSITION="right">
          <edge STYLE="bezier" COLOR="#715344" WIDTH="4"/>
          <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
        </node>
        <node ID="id_7" TEXT="Syntax" FOLDED="false" COLOR="#715344" POSITION="right">
          <edge STYLE="bezier" COLOR="#715344" WIDTH="4"/>
          <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
        </node>
        <node ID="id_8" TEXT="Read" FOLDED="false" COLOR="#715344" POSITION="right">
          <edge STYLE="linear" COLOR="#715344" WIDTH="4"/>
          <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          <node ID="id_9" TEXT="Books" FOLDED="false" COLOR="#715344" POSITION="right">
            <edge STYLE="bezier" COLOR="#715344" WIDTH="4"/>
            <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          </node>
          <node ID="id_10" TEXT="Poem" FOLDED="false" COLOR="#715344" POSITION="right">
            <edge STYLE="bezier" COLOR="#715344" WIDTH="4"/>
            <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          </node>
          <node ID="id_11" TEXT="Dialogue and Subtitles" FOLDED="false" COLOR="#715344" POSITION="right">
            <edge STYLE="bezier" COLOR="#715344" WIDTH="4"/>
            <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          </node>
        </node>
        <node ID="id_12" TEXT="Listen" FOLDED="false" COLOR="#715344" POSITION="right">
          <edge STYLE="linear" COLOR="#715344" WIDTH="4"/>
          <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          <node ID="id_13" TEXT="Podcasts" FOLDED="false" COLOR="#715344" POSITION="right">
            <edge STYLE="bezier" COLOR="#715344" WIDTH="4"/>
            <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          </node>
          <node ID="id_14" TEXT="Dialogue (movies and games" FOLDED="false" COLOR="#715344" POSITION="right">
            <edge STYLE="bezier" COLOR="#715344" WIDTH="4"/>
            <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          </node>
        </node>
      </node>
      <node ID="id_15" TEXT="Write" FOLDED="false" COLOR="#4e9a06" POSITION="right">
        <edge STYLE="bezier" COLOR="#4e9a06" WIDTH="4"/>
        <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
        <node ID="id_16" TEXT="Phrases" FOLDED="false" COLOR="#4e9a06" POSITION="right">
          <edge STYLE="bezier" COLOR="#4e9a06" WIDTH="4"/>
          <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
        </node>
        <node ID="id_17" TEXT="Poem" FOLDED="false" COLOR="#4e9a06" POSITION="right">
          <edge STYLE="bezier" COLOR="#4e9a06" WIDTH="4"/>
          <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
        </node>
        <node ID="id_18" TEXT="Chat with people" FOLDED="false" COLOR="#4e9a06" POSITION="right">
          <edge STYLE="bezier" COLOR="#4e9a06" WIDTH="4"/>
          <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
        </node>
      </node>
      <node ID="id_19" TEXT="Talk" FOLDED="false" COLOR="#3689e6" POSITION="right">
        <edge STYLE="bezier" COLOR="#3689e6" WIDTH="4"/>
        <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
        <node ID="id_20" TEXT="Talk with yourself" FOLDED="false" COLOR="#3689e6" POSITION="right">
          <edge STYLE="bezier" COLOR="#3689e6" WIDTH="4"/>
          <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
        </node>
        <node ID="id_21" TEXT="Repeat with dialogue " FOLDED="false" COLOR="#3689e6" POSITION="right">
          <edge STYLE="bezier" COLOR="#3689e6" WIDTH="4"/>
          <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
        </node>
        <node ID="id_22" TEXT="Talk with strange people" FOLDED="false" COLOR="#3689e6" POSITION="right">
          <edge STYLE="bezier" COLOR="#3689e6" WIDTH="4"/>
          <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
        </node>
      </node>
    </node>
    <node ID="id_23" TEXT="Learning Linux" FOLDED="false" COLOR="#f9c440" POSITION="right">
      <edge STYLE="bezier" COLOR="#f9c440" WIDTH="4"/>
      <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
      <node ID="id_24" TEXT="GUI" FOLDED="false" COLOR="#f9c440" POSITION="right">
        <edge STYLE="bezier" COLOR="#f9c440" WIDTH="4"/>
        <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
        <node ID="id_25" TEXT="Understand Interface" FOLDED="false" COLOR="#f9c440" POSITION="right">
          <edge STYLE="bezier" COLOR="#f9c440" WIDTH="4"/>
          <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
        </node>
        <node ID="id_26" TEXT="Edit things from gui" FOLDED="false" COLOR="#f9c440" POSITION="right">
          <edge STYLE="linear" COLOR="#f9c440" WIDTH="4"/>
          <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          <node ID="id_27" TEXT="Users" FOLDED="false" COLOR="#f9c440" POSITION="right">
            <edge STYLE="bezier" COLOR="#f9c440" WIDTH="4"/>
            <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          </node>
          <node ID="id_28" TEXT="Password" FOLDED="false" COLOR="#f9c440" POSITION="right">
            <edge STYLE="bezier" COLOR="#f9c440" WIDTH="4"/>
            <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          </node>
          <node ID="id_29" TEXT="Permissions" FOLDED="false" COLOR="#f9c440" POSITION="right">
            <edge STYLE="bezier" COLOR="#f9c440" WIDTH="4"/>
            <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          </node>
          <node ID="id_30" TEXT="etc..." FOLDED="false" COLOR="#f9c440" POSITION="right">
            <edge STYLE="bezier" COLOR="#f9c440" WIDTH="4"/>
            <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          </node>
        </node>
      </node>
      <node ID="id_31" TEXT="CLI" FOLDED="false" COLOR="#310519" POSITION="right">
        <edge STYLE="bezier" COLOR="#310519" WIDTH="4"/>
        <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
        <node ID="id_32" TEXT="Shortcuts Terminal" FOLDED="false" COLOR="#310519" POSITION="right">
          <edge STYLE="bezier" COLOR="#310519" WIDTH="4"/>
          <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
        </node>
        <node ID="id_33" TEXT="Difference Shell" FOLDED="false" COLOR="#310519" POSITION="right">
          <edge STYLE="linear" COLOR="#310519" WIDTH="4"/>
          <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          <node ID="id_34" TEXT="Bash" FOLDED="false" COLOR="#310519" POSITION="right">
            <edge STYLE="bezier" COLOR="#310519" WIDTH="4"/>
            <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          </node>
          <node ID="id_35" TEXT="Zsh" FOLDED="false" COLOR="#310519" POSITION="right">
            <edge STYLE="bezier" COLOR="#310519" WIDTH="4"/>
            <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          </node>
          <node ID="id_36" TEXT="Fish" FOLDED="false" COLOR="#310519" POSITION="right">
            <edge STYLE="bezier" COLOR="#310519" WIDTH="4"/>
            <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          </node>
        </node>
        <node ID="id_37" TEXT="Command Line" FOLDED="false" COLOR="#310519" POSITION="right">
          <edge STYLE="linear" COLOR="#310519" WIDTH="4"/>
          <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          <node ID="id_38" TEXT="File and Directories" FOLDED="false" COLOR="#310519" POSITION="right">
            <edge STYLE="bezier" COLOR="#310519" WIDTH="4"/>
            <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          </node>
          <node ID="id_39" TEXT="Users and Permissions" FOLDED="false" COLOR="#310519" POSITION="right">
            <edge STYLE="bezier" COLOR="#310519" WIDTH="4"/>
            <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          </node>
          <node ID="id_40" TEXT="Tools" FOLDED="false" COLOR="#310519" POSITION="right">
            <edge STYLE="bezier" COLOR="#310519" WIDTH="4"/>
            <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          </node>
          <node ID="id_41" TEXT="Configuration" FOLDED="false" COLOR="#310519" POSITION="right">
            <edge STYLE="bezier" COLOR="#310519" WIDTH="4"/>
            <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          </node>
          <node ID="id_42" TEXT="Shell Scripts" FOLDED="false" COLOR="#310519" POSITION="right">
            <edge STYLE="bezier" COLOR="#310519" WIDTH="4"/>
            <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
          </node>
        </node>
      </node>
      <node ID="id_43" TEXT="Folders and Files system" FOLDED="false" COLOR="#4d4a4a" POSITION="right">
        <edge STYLE="bezier" COLOR="#4d4a4a" WIDTH="4"/>
        <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
        <node ID="id_44" TEXT="Structure of files and folders" FOLDED="false" COLOR="#4d4a4a" POSITION="right">
          <edge STYLE="bezier" COLOR="#4d4a4a" WIDTH="4"/>
          <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
        </node>
        <node ID="id_45" TEXT="The cause of the and files" FOLDED="false" COLOR="#4d4a4a" POSITION="right">
          <edge STYLE="bezier" COLOR="#4d4a4a" WIDTH="4"/>
          <font NAME="Manjari" SIZE="13" BOLD="false" ITALIC="false"/>
        </node>
      </node>
    </node>
  </node>
</map>
